version: "3.8"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/ansulist/goinfre/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /Users/ansulist/goinfre/data/wordpress
      o : bind
      type : none

networks:
  inception:
    name: inception
    driver: bridge

services:
#mariadb
  mariadb:
    image: mariadb:ansulist
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s  # Wait for MariaDB to start up before checking
#nginx
  nginx:
    image: nginx:ansulist
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:ansulist
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always
