events {
	
}

http {

	include /etc/nginx/mime.types;
	server {
		#Configures NGINX to listen on port 443 (HTTPS) and handle SSL connections.
		listen 443 ssl;
		#Specify the paths to the SSL certificate and private key.
		ssl_certificate  /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;
		ssl_protocols TLSv1.3;

		#Points to the directory where WordPress files are located.
		root /var/www/wordpress;
		#Sets the domain name for the server (using the environment variable).
		server_name $DOMAIN_NAME;
		index index.php;
		#handles PHP requests
		location ~ \.php$ {
			#Forwards PHP requests to the WordPress container on port 9000, where PHP-FPM is running
			include snippets/fastcgi-php.conf;
			#Includes configuration for handling FastCGI (for PHP processing).
			fastcgi_pass wordpress:9000;
		}
	}
}